### ISSUE TITLE
Channel Points no showing up (Even when toggled on)

### ISSUE THREAD

**Issue by TheeMekoChan** [baffler/Transparent-Twitch-Chat-Overlay#237]
I have them toggled on, but they're not showing up

**Comment by SoloSwain** [comment]
yeah i am having the same problem i tried everything to fix it, it been like this since the new version

**Comment by 10burgers** [comment]
Still happening with the newest update; just to keep everyone up to date

**Comment by SoloSwain** [comment]
Yeah I went back to an older version that makes it work till they fix it

**Comment by baffler** [comment]
This is fixed in [v1.0.4](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.4)

**Comment by SoloSwain** [comment]
I went and had a test with 1.0.4 and it still doesn't work to let ya know
